[tool.poetry]
name = "py-golf-games"
version = "0.0.0"
description = "Simulation of golf games"
authors = ["Ryan <ryankanno@localkinegrinds.com>"]
packages = [
    { include = "py_golf_games" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-isort = "^4.1.2"
isort = "^5.10.1"
mypy = "^0.971"
pdbpp = "^0.10.3"
pre-commit = "^2.20.0"
pytest = "^7.1.2"
pytest-black = "^0.3.12"
pytest-cov = "^3.0.0"
pytest-flake8 = "^1.1.1"
pytest-mock = "^3.8.2"
pytest-mypy = "^0.9.1"
pytest-randomly = "^3.12.0"
pytest-xdist = "^2.5.0"
tox = "^3.25.1"
black = "^22.6.0"

[tool.black]
line-length = 79
skip-string-normalization = true
target_version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.direnv
     | \.eggs
     | \.git
     | \.hg
     | \.mypy_cache
     | \.nox
     | \.tox
     | \.venv
     | venv
     | \.svn
     | _build
     | buck-out
     | build
     | dist
     | __pypackages__
     | \{\{cookiecutter\.package_name\}\}\/tests
 )/
)
'''

[tool.isort]
force_grid_wrap = 0
force_single_line = true
include_trailing_comma = true
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true
known_third_party = []
default_section = "THIRDPARTY"
known_first_party = "py_golf_games"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
