[tool.poetry]
name = "py-golf-games"
version = "0.0.0"
description = "Simulation of golf games"
authors = ["Ryan <ryankanno@localkinegrinds.com>"]
maintainers = ["Ryan <ryankanno@localkinegrinds.com>"]
readme = "README.rst"
packages = [
    { include = "py_golf_games" },
]
include = [
    { path = "tests", format = "sdist" },
    { path = "LICENSE" }
]

repository = "https://github.com/ryankanno/py-golf-games"
keywords = ["golf"]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
]

[tool.poetry.dependencies]
python = "^3.8"
structlog = ">=21.1,<23.0"

[tool.poetry.dev-dependencies]
dunamai = "^1.15.0"
flake8 = "^5.0.4"
flake8-isort = "^5.0.3"
ipython = "^8.8.0"
isort = "^5.11.4"
konch = "^4.2.2"
mypy = "^0.991"
pdbpp = "^0.10.3"
pre-commit = "^2.21.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-randomly = "^3.12.0"
pytest-xdist = "^3.1.0"
sphinx = "^6.1.1"
tox = "^4.2.4"
black = "^22.12.0"
hypothesis = "^6.61.0"
mutmut = "^2.4.3"

[tool.mypy]
python_version = "3.8"
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = "normal"
ignore_missing_imports = true
no_implicit_optional = true
no_implicit_reexport = false
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = false

[tool.black]
line-length = 79
skip-string-normalization = true
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.direnv
     | \.eggs
     | \.git
     | \.hg
     | \.mypy_cache
     | \.nox
     | \.tox
     | \.venv
     | venv
     | \.svn
     | _build
     | buck-out
     | build
     | dist
     | __pypackages__
     | \{\{cookiecutter\.package_name\}\}\/tests
 )/
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -n auto"

[tool.coverage.run]
parallel = true
branch = true
source = ["py_golf_games"]
omit = [
    "*/python?.?/*",
    "*/tests/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "import",
]
show_missing = true
skip_covered = false

[tool.isort]
force_grid_wrap = 0
force_single_line = true
include_trailing_comma = true
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true
known_third_party = []
default_section = "THIRDPARTY"
known_first_party = "py_golf_games"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.vulture]
make_whitelist = true
min_confidence = 80
paths = ["py_golf_games", "tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
